In [ ]:
# 1. What is a Python library? Why do we use Python libraries?
# Collection of functions
# functions can be reused
# why?
# Python libraries contains optimized functions because lot of testing is done on python libraries

In [ ]:
# 2. What is the difference between Numpy array and List? 
# List has dynamic size or resizing in nature.
# List has to check space and data type when adding elements
# Array doesn't have to check space and data type when adding elements because 
# elements are homogenous and space is static defined in array, that is reason array is faster
# array is statically defined contigous memory allocation and fixed size in nature
# Array and List are mutable

In [5]:
# 3. Find the shape, size and dimension of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]
import numpy as np
arr=[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

# Shape
print("Shape: ",np.shape(arr))

# Size
print("Size: ",np.size(arr))

# Dimension
print("Dimension: ",np.ndim(arr))

Shape:  (3, 4)
Size:  12
Dimension:  2


In [13]:
# 4. Write python code to access the first row of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

arr=[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

print(arr[0])

[1, 2, 3, 4]


In [40]:
# 5. How do you access the element at the third row and fourth column from the given numpy array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

arr=[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

np_arr=np.array(arr)

np_arr[2, [3]]

array([12])

In [43]:
# 6. Write code to extract all odd-indexed elements from the given numpy array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

arr=[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

np_arr=np.array(arr)

np_arr[0:3 , [0,3]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [46]:
# 7. How can you generate a random 3x3 matrix with values between 0 and 1?

arr1 = np.random.randint(0, 2, (3,3))
arr1

array([[1, 0, 1],
       [0, 0, 1],
       [0, 0, 1]])

In [ ]:
# 8. Describe the difference between np.random.rand and np.random.randn?

np.random.rand(1) # generate random values from given number 0 to 1
np.random.rand(2, 3) # generate 2x3 random float values

np.random.randn(2, 3) # Return a sample (or samples) from the "standard normal" distribution.

In [52]:
# 9. Write code to increase the dimension of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

arr=[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

np_arr=np.array(arr)

np_arr.reshape(1,3,4) # reshape from 2D array to 3D array repeated 1 time of 3 rows and 4 columns

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [53]:
# 10. How to transpose the following array in NumPy?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

arr=[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

np_arr=np.array(arr)

np_arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [78]:
# 11. Consider the following matrix:
# Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
# Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
# Perform the following operation using Python1
# 1. Index wise multiplication
# 2. Matix multiplication
# 3. Add both the matices
# 4. Subtact matix B from A
# 5. Divide Matix B by A

import numpy as np

A2 = [[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]
B2 = [[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]

A=np.array(A2)
B=np.array(B2)

# Index wise multiplication
Index_product = np.multiply(A,B)
print("Index wise multiplication:\n", Index_product)
print()

# Matix multiplication
# Here A2 and B2 arrays has 3 rows and 4 columns, where if we have to do matrix multiplication
# then A2 = 3 x 4 , B2 = 3 X 4 , which is not possible
# to perform matrix multiplication B2 should be converted into transpose matrix
# the A2 and B2 are elgible to perform matrix multiplication
matrix_product = A @ B.T
print("Matrix multiplication:\n", matrix_product)
print()

# Add both matrices
Add = A + B
print("Addition of both matrices:\n", Add)
print()

# Subtract matrices from B - A
Sub = B - A
print("Subtraction of both matrices:\n", Sub)
print()

# Divide matrices from B / A
Div = B // A
print("Divide of both matrices:\n", Div)
print()

Index wise multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

Matrix multiplication:
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

Addition of both matrices:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Subtraction of both matrices:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Divide of both matrices:
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]



In [79]:
# 12. Which function in Numpy can be used to swap the byte order of an array?
# In NumPy, the byteswap function can be used to swap the byte order of an array. 
# The byteswap function returns a new array with the byte order swapped. 
# You can specify the byte order using the byteorder parameter.

import numpy as np

# Create an example array
original_array = np.array([1, 2, 3, 4], dtype=np.int32)

# Swap the byte order
swapped_array = original_array.byteswap()

# Print the original and swapped arrays
print("Original Array:")
print(original_array)
print("\nSwapped Array:")
print(swapped_array)

Original Array:
[1 2 3 4]

Swapped Array:
[16777216 33554432 50331648 67108864]


In [80]:
# 13. What is the significance of the np.linalg.inv function?

# The np.linalg.inv function in NumPy is used to compute the (multiplicative) inverse of a square matrix. 
# In mathematical terms, if A is a square matrix, then the matrix B such that A @ B = B @ A = I, where I is the identity matrix, 
# is called the inverse of matrix A. 
# Not all matrices have an inverse, and a matrix must be square (having the same number of rows and columns) to have an inverse.

# The significance of np.linalg.inv lies in its applications in linear algebra, solving systems of linear equations, and 
# various numerical methods.

import numpy as np

# Coefficient matrix A
A = np.array([[2, 1],
              [3, 4]])

# Constant matrix B
B = np.array([4, 7])

# Solve for x in Ax = B
x = np.linalg.inv(A) @ B

print("Solution vector x:", x)

Solution vector x: [1.8 0.4]


In [82]:
# 14. What does the np.reshape function do, and how is it used?
# The np.reshape function in NumPy is used to change the shape of an array without changing its data. 
# It allows you to give a new shape to an array without modifying its data, as long as the new shape has 
# the same number of elements as the original shape.

# The basic syntax of np.reshape is: numpy.reshape(a, newshape, order='C')
# a: The array to be reshaped.
# newshape: The new shape to be given to the array. It should be compatible with the original shape.
# order: Optional. Specifies the order in which the elements of the array should be read. It can be 'C' (row-major, default) or 'F' (column-major).

# Example of how to use np.reshape:

import numpy as np

# Create a 1D array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array to a 2D array (2 rows, 3 columns)
reshaped_array = np.reshape(original_array, (2, 3))

print("Original Array:")
print(original_array)

print("\nReshaped Array:")
print(reshaped_array)

Original Array:
[1 2 3 4 5 6]

Reshaped Array:
[[1 2 3]
 [4 5 6]]


In [83]:
# 15. What is broadcasting in Numpy?
# Broadcasting in NumPy is a powerful mechanism that allows NumPy to perform operations on arrays of different shapes and sizes. 
# It enables the element-wise operations between arrays of different shapes without explicitly reshaping them, 
# making the code more concise and readable.

# The broadcasting rules in NumPy allow arrays with different shapes to be combined in a way that makes sense. 
# The smaller array is "broadcast" across the larger array so that they have compatible shapes. 
# The following rules are applied during broadcasting:

# Rule 1: 
# Size Compatibility: The dimensions of the arrays are compared element-wise. Two dimensions are compatible when:
# They are equal, or One of them is 1.

# Rule 2: 
# Size of 1: If one of the arrays has size 1 in a particular dimension, 
# it is "stretched" to match the size of the other array in that dimension.

# Rule 3: 
# Missing Dimensions: If the arrays have a different number of dimensions, missing dimensions are assumed to have a size of 1.

import numpy as np

# Create a 2x3 array
A = np.array([[1, 2, 3], [4, 5, 6]])

# Add a scalar (broadcasting)
result = A + 10

print(result)

[[11 12 13]
 [14 15 16]]
